### ISSUE TITLE
Can we use setOnSeekBarChangeListener? 

### ISSUE THREAD

**Issue by Telpr2** [AnderWeb/discreteSeekBar#13]
Hi I am new to android. Just checked your library. Can we use setOnSeekBarChangeListener in your seekbar? If so how? Awaiting your response at the earliest.
Thanks in advance.

**Comment by ignaciogs** [comment]
Use the setOnProgressChangeListener method

**Comment by Telpr2** [comment]
Thank you. Can we tilt the balloon left or right as per the pull? If so how to go about with this?

**Comment by Telpr2** [comment]
I meant the marker.... Can we tilt it? Awaiting for earliest response.

**Comment by Telpr2** [comment]
Can anyone help me in clearing this doubt?

**Comment by AOrobator** [comment]
I don't think so. If you wanted to do that yourself, you'd have to code it yourself and then do a pull request

**Comment by Telpr2** [comment]
Sorry couldn't get your reply. Can you please explain me how to go about with that?

**Comment by tobybonhof** [comment]
the onprogresschanged listener does not have a start tracking and end tracking. How can we enable this or achieve the same effect

**Comment by ignaciogs** [comment]
I think that you can add a new method to the public interface (OnProgressChangeListener) or create a new interface and call those new methods in startDragging and stopDragging methods. But I'm not sure that's the best solution

**Comment by AnderWeb** [comment]
Closing as the Listener interface already has the tracking methods
