### ISSUE TITLE
Indicator dismisses before releasing touch.

### ISSUE THREAD

**Issue by ladjzero** [AnderWeb/discreteSeekBar#19]
Thank you for such nice component!

This issue happens on my device galaxy S2, android 4.0.4. But everything is OK on my another device which runs 4.2.2.

Indicator pops up as soon as I touch it, and then dismisses quickly before I release or begin to drag.

I guess `hideFloater` was invoked by accident before my releasing. I debugged. It turns out that I'm wrong.

Any idea? Thank you.

**Comment by AnderWeb** [comment]
Would you try to reproduce the issue using an emulator with 4.0.4 instead of a real device? Please report back, thanks!

**Comment by ladjzero** [comment]
![repro](http://ww2.sinaimg.cn/mw690/49b96255gw1eptyn49012g208702pb00.gif)

I reproduced on an emulator. A bug indeed.

**Comment by AnderWeb** [comment]
Thanks, I'll take a look into it.
