### ISSUE TITLE
Request - Disabled Theme

### ISSUE THREAD

**Issue by TurKurT656** [AnderWeb/discreteSeekBar#21]
Hi Bro
This is a great and amzing lib.
but when i disable seekBar the colors still same as when they are enabled. can u set them to grey?

**Comment by AnderWeb** [comment]
You already can provide state-aware colors if you use color selectors for the color properties.
Check the included [sample](https://github.com/AnderWeb/discreteSeekBar/blob/master/sample/src/main/res/layout/activity_main.xml#L30)
