### ISSUE TITLE
Request - Gradle

### ISSUE THREAD

**Issue by TurKurT656** [AnderWeb/discreteSeekBar#22]
Great and a complete lib.
wish to use this lib with Gradle :+1:

**Comment by vyscond** [comment]
+1 for this

**Comment by jmvines** [comment]
+1 thanks!

**Comment by formatBCE** [comment]
+1 too, thanks!

**Comment by OlegWock** [comment]
+1

**Comment by Ph1b** [comment]
+1 Really hate to maintain repos manually

**Comment by wangbourne** [comment]
|1

**Comment by emanuelet** [comment]
+1.
As a temporary solution you can use 
```
compile 'com.github.AnderWeb:discreteSeekBar:a3b5deadf3'
```
with jitpack.io as a repo guys.

**Comment by emanuelet** [comment]
on that note, even without been publish on some other repo, will be helpful to create a release with the version

**Comment by AnderWeb** [comment]
Sorry guys, it's been a tough time.
I'll try to create a bintray account and upload the lib.

**Comment by AOrobator** [comment]
Better late than never :) Thanks for the work, and sorry about your mom.

**Comment by HeinrichReimer** [comment]
@AnderWeb Thank you so much for this awsome `SeekBar`. I'm using it in my library <a href="https://github.com/HeinrichReimer/material-singleinputform">**material-singleinputform**</a> and I'm really happy you'll upload it to jCenter or Maven Central.

**Comment by wangbourne** [comment]
Thanks

**Comment by TurKurT656** [comment]
TnQ veri mach :D

**Comment by emanuelet** [comment]
thanks very much

**Comment by formatBCE** [comment]
Thanks a lot!!!

**Comment by AnderWeb** [comment]
Closing this, already published to jCenter
