### ISSUE TITLE
How to change progress color for disabled DiscreteSeekBar?

### ISSUE THREAD

**Issue by Dhaval2404** [AnderWeb/discreteSeekBar#28]
I am using DiscreteSeekBar, And it is working like a charm. I want to change the progress color of DiscreteSeekBar if it is in disabled state. How can i do that? Any hint will be appreciated. Thanks for this awesome libarary.  :+1:

**Comment by AOrobator** [comment]
Try using a [ColorStateList](http://developer.android.com/reference/android/content/res/ColorStateList.html) as the color for you seekbar.

**Comment by Dhaval2404** [comment]
@AOrobator Thanks for your answer.  You saved my day :-)

**Comment by AOrobator** [comment]
Glad to help :)
