### ISSUE TITLE
Basic Tap to set Progress of Seek Bar is not Working

### ISSUE THREAD

**Issue by Sai-Teja** [AnderWeb/discreteSeekBar#37]
Plz make sure this works this is the basic functionality of a seek bar user will get irritated if this doesn't work. Plz do it ASAP.

**Comment by Sai-Teja** [comment]
Found a Solution! This can be fixed by setting touch slop to 0. So, plz add appropriate setters and getters for that! in the next update

**Comment by AOrobator** [comment]
You should write a pull-request if it's that important to you. That way it'll be included in the code base much faster.

**Comment by xsorifc28** [comment]
@Sai-Teja Could you provide a detailed solution?

I'm also having the same issue. Can't set the progress by tapping.

**Comment by Yamko** [comment]
is this problem fixed?

**Comment by Sai-Teja** [comment]
@xsorifc28 Sorry for the Delay! I was quite Busy! I have issued a Pull Request It might be merged soon!
@Yamko Yes, It is Fixed!
