### ISSUE TITLE
Seek on single touch

### ISSUE THREAD

**Issue by vivekkartha** [AnderWeb/discreteSeekBar#47]
The seekbar does not move to the touched position , instead user is forced to touch and move a bit. This behaviour greatly affects the user experience. 
Could you please make it seek-on-click? Any solutions for this?

**Comment by AOrobator** [comment]
You could always set an OnClickListener for the track, get the X coords for the touch event then update the seekbar as necessary. Pull-requests welcome.

**Comment by Sai-Teja** [comment]
@vivekkartha Check out my issue I have fixed the issue but my pull request it is still not merged dunno why... @AnderWeb Merge it ASAP

https://github.com/AnderWeb/discreteSeekBar/issues/37

**Comment by vivekkartha** [comment]
I did not understand your fix Sai Teja

**Comment by Sai-Teja** [comment]
Just make touch slop -1 that's all you need to understand the rest of for adding xml attribute. Add the library as a module nd make the change and it will work

**Comment by Sai-Teja** [comment]
Did u check d pull request btw?
