### ISSUE TITLE
continuous mode

### ISSUE THREAD

**Issue by wangbourne** [AnderWeb/discreteSeekBar#48]
onProgressChanged is currently called multiple times during a sliding action. It's better to have an option of continuous = false/true. If  continuous = false, onProgressChanged is only called when sliding is finished.

**Comment by ignaciogs** [comment]
Hi:

You can use the method onStopTrackingTouch (DiscreteSeekBar.OnProgressChangeListener). This method is only called when sliding is finished.

Cheers

**Comment by wangbourne** [comment]
thanks:)
