### ISSUE TITLE
It is better for this library to extend the original SeekBar , isn't it?

### ISSUE THREAD

**Issue by aebmgroup** [AnderWeb/discreteSeekBar#52]
I used this library for a while , it is nice but in some situations it doesn't acts like the original SeekBar.
For example: when i call setMax() in runtime , it only changes maximum amount and doesn't regulate current slider position (progress) but the original SeekBar does. 
An easy way to fix this problem , is to extend the original SeekBar Widget , many other problems will solve easily too. of course i'm sure you knew this solution , maybe you can't do this because of other interference or technical issues , but think again about it. :) 
Thanks for your great work and sorry for my bad English , it isn't my native language.

**Comment by AnderWeb** [comment]
The first thing I tried when creating this component was to extend SeekBar. But it didn't allow me to hook up on touch handling and other stuff to get the position where the indicator should go.

If there is a problem with the behaviour of setMin or setMax, we can try and fix it though. Just please indicate a way to reproduce it (using the sample app code would be great) and we'll find a solution.
