### ISSUE TITLE
cannot resolve dependency

### ISSUE THREAD

**Issue by a1154043439** [AnderWeb/discreteSeekBar#55]
i want to use these seekbar in my project,I write this in my build.gradle
dependencies{
  compile 'org.adw.library:discrete-seekbar:1.0.0'
}
and my  gradle sync complete without mistakes.
but i cannot import org.adw.samples.discretseekbar,what's wrong with my code?

**Comment by ignaciogs** [comment]
Try this import 

org.adw.library.widgets.discreteseekbar.DiscreteSeekBar

**Comment by a1154043439** [comment]
thank you for your suggestion,it's not work either,i think i cannot find this library in my External Libraries,so 
android studio cannot auto import,if my gradle is correct,why i cannot resolve this dependency

**Comment by ignaciogs** [comment]
I think that if gradle sync completed without mistakes, the problem is with the Android Studio sync. Try  do a clean and rebuid project

**Comment by a1154043439** [comment]
I have resloved this problem according to your opinion,Thank you very much

**Comment by ignaciogs** [comment]
you're welcome  ;)
