### ISSUE TITLE
Set min and max programmatically

### ISSUE THREAD

**Issue by sahana-tib** [AnderWeb/discreteSeekBar#60]
How to set min and max value and current value programmatically? I tried like the below snippet. the indicator dint appear.

         prepTimeBar.setMin(0);
         prepTimeBar.setMax(100);

**Comment by ignaciogs** [comment]
I tested setMin() and setMax() methods and works fine. Are you using some NumericTransformer?

**Comment by sahana-tib** [comment]
Worked with the same methods. thanks :)

On 25 January 2016 at 18:11, Ignacio <notifications@github.com> wrote:

> I tested setMin() and setMax() methods and works fine. Are you using some
> NumericTransformer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AnderWeb/discreteSeekBar/issues/60#issuecomment-174495126>
> .
>



-- 
Regards,
Sahana
