### ISSUE TITLE
setting value as some string like "3:40".

### ISSUE THREAD

**Issue by Jayiitb** [AnderWeb/discreteSeekBar#68]
Hi @AnderWeb 

I wanted to set value as "3:40" min for the player playing. But NumericTransformer return value is int and value is of integer type, that is not possible. Can you plz support this?

Thanks,
Jay Prakash

**Comment by Jayiitb** [comment]
@AnderWeb after looking closely, found you already have string feature enabled.
Thanks a lot for this wonderful work.

**Comment by guisantogui** [comment]
Hi @Jayiitb, I'm looking for the same, feature, where did you found it?
