### ISSUE TITLE
Change size of indicator

### ISSUE THREAD

**Issue by HassanJawed** [AnderWeb/discreteSeekBar#7]
I want to change the size of indicator in order to adjust my text there, I reduced textSize to 8sp but it is still trimming. How can I change the size of indicator or more specifically PopupIndicator.
Another thing, I add drawable to indicator instead of color, is it possible and how?

Thanks in advance.

**Comment by Ph1b** [comment]
I think this could be related to https://github.com/AnderWeb/discreteSeekBar/issues/32

**Comment by AnderWeb** [comment]
Closing and moved to #32
