### ISSUE TITLE
Spot pair overflow!!!

### ISSUE THREAD

**Issue by Mantoska** [AnderWeb/discreteSeekBar#78]
An error occurs on Android 6.0 (Marshmallow), device Sony Xperia Z5. It happens when you tap the progress button multiple times and sometimes when you slide it back and forth without releasing it.

![screenhunter_111 apr 19 12 26](https://cloud.githubusercontent.com/assets/7621072/14634378/50b8f1b0-062a-11e6-9bd0-78bad35ef720.jpg)

Anyone knows a solution?

**Comment by AnderWeb** [comment]
Seems a duplicate of issue #73

**Comment by jaswant0605** [comment]
app:cardElevation="0dp"

I had a similar type of issue, i was using a cardview and I resolved it by setting the elevation of the cardview to 0 dp, I hope it will work.
