### ISSUE TITLE
Floaty Thing clipped on sides

### ISSUE THREAD

**Issue by AOrobator** [AnderWeb/discreteSeekBar#8]
When dragging the seekbar quickly, the floaty thing gets clipped on the sides. I'm assuming this is because the view window isn't large enough or something like that. A proposed fix would be to alter the window manager code so that the bubble floaty thing is allowed to draw on the entire width of the seekbar

**Comment by AnderWeb** [comment]
Could you provide a working sample (layout or whatever) to reproduce the issue?
Whe floating thing's window is currently using the whole screen's width so the clipping shouldn't happen (or at least I've been unable to reproduce it)

**Comment by AOrobator** [comment]
The current layout I'm using that has issues is provided below. The seekbar is closer towards the bottom. Mayhaps it's the fact that it's in nested views? I've taken a look at the screen with show layout bounds on, and it's showing something very different for this layout, vs. a simpler layout where it's literally just a RelativeLayout with the seekbar centered in the layout. The following may be a clue to the solution of this problem, I don't know very much about Window Management, but it seems like the issue lies with it. For the layout bounds of both layouts, there is a bound around the TextView that contains the numbers for the indicator text, as well as a bound for the actual popup indicator. In the layout below, the bound for the popup indicator moves when the seekbar drags, so I'm assuming that since the bounds are moving along with the indicator, it's being clipped if the bounds move too fast. On the simpler layout, the bound for the popup indicator stayed in the middle of the seekbar while the popup indicator moved left and right (user performing seek action). I'm assuming the simpler layout didn't clip because the bound for the popup indicator never actually moved but stayed in the center, so was unable to clip the popup indicator

    <?xml version="1.0" encoding="utf-8"?>

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

    <RelativeLayout
        android:id="@+id/now_playing_card"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerVertical="true"
        android:background="@drawable/now_playing_miniplayer_card">

        <RelativeLayout
            android:id="@+id/headerLayout"
            android:layout_width="match_parent"
            android:layout_height="88dp"
            android:layout_marginLeft="8dp"
            android:layout_marginRight="8dp"
            android:layout_marginTop="8dp">

            <ImageButton
                android:id="@+id/popMenuAnchor_ImageButton"
                style="?android:attr/borderlessButtonStyle"
                android:layout_width="40dp"
                android:layout_height="48dp"
                android:layout_alignParentEnd="true"
                android:src="@drawable/now_playing_card_overflow"
                android:tint="@color/album_song_track_number_color"/>

            <de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/artist_ImageView"
                android:layout_width="50dp"
                android:layout_height="50dp"
                android:layout_centerVertical="true"
                android:layout_margin="11dp"
                android:contentDescription="@string/now_playing_content_description_artist_image"
                android:src="@drawable/artist_image_placeholder"
                app:border_color="@color/white"
                app:border_width="0dp"/>

            <ImageButton
                android:id="@+id/artistFrame_ImageButton"
                style="?android:attr/borderlessButtonStyle"
                android:layout_width="64dp"
                android:layout_height="64dp"
                android:layout_marginStart="3.5dp"
                android:layout_centerVertical="true"
                android:contentDescription="@string/now_playing_content_description_artist_image"
                android:src="@drawable/artist_image_frame"/>

            <LinearLayout
                android:id="@+id/headerTextLayout"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_toEndOf="@id/artist_ImageView"
                android:orientation="vertical">

                <TextView
                    android:id="@+id/title_TextView"
                    style="@style/SongTextPrimary"
                    android:layout_marginEnd="12dp"
                    android:paddingEnd="20dp"
                    android:textSize="18sp"
                    tools:text="Sample title"/>

                <TextView
                    android:id="@+id/artist_TextView"
                    style="@style/SongTextSecondary"
                    android:layout_marginEnd="12dp"
                    android:paddingEnd="20dp"
                    android:textSize="14sp"
                    tools:text="Sample artist"/>

                <TextView
                    android:id="@+id/album_TextView"
                    style="@style/SongTextSecondary"
                    android:layout_marginEnd="12dp"
                    android:paddingEnd="20dp"
                    android:textSize="14sp"
                    tools:text="Sample album"/>
            </LinearLayout>


        </RelativeLayout>

        <RelativeLayout
            android:id="@+id/albumArtLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/headerLayout"
            android:layout_marginLeft="8dp"
            android:layout_marginRight="8dp">

            <ImageView
                android:id="@+id/album_art_ImageView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignParentStart="true"
                android:layout_alignParentEnd="true"
                android:src="@drawable/album_art_placeholder"/>

            <View
                android:layout_width="match_parent"
                android:layout_height="0.5dp"
                android:background="@color/notification_divider_gray"/>

            <ImageView
                android:id="@+id/nowPlayingPlayPause_ImageView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignParentStart="true"
                android:layout_alignParentEnd="true"
                android:layout_centerInParent="true"
                android:maxHeight="144dp"
                android:maxWidth="144dp"
                android:src="@drawable/now_playing_play"/>
        </RelativeLayout>

        <RelativeLayout
            android:id="@+id/footerLayout"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:layout_below="@id/albumArtLayout"
            android:layout_marginBottom="8dp"
            android:layout_marginLeft="8dp"
            android:layout_marginRight="8dp">

            <TextView
                android:id="@+id/nowPlayingMetadata_TextView"
                style="@style/SongTextSecondary"
                android:layout_height="match_parent"
                android:layout_centerVertical="true"
                android:layout_toStartOf="@+id/nowPlayingTimeLeft_textView"
                android:layout_toEndOf="@+id/nowPlayingTimePlayed_textView"
                android:gravity="center"
                tools:text="Played 9,001 times"/>

            <TextView
                android:id="@+id/nowPlayingTimePlayed_textView"
                style="@style/SongTextSecondary"
                android:layout_alignParentStart="true"
                android:layout_centerVertical="true"
                android:layout_marginStart="16dp"
                tools:text="00:00"/>

            <TextView
                android:id="@id/nowPlayingTimeLeft_textView"
                style="@style/SongTextSecondary"
                android:layout_alignParentEnd="true"
                android:layout_centerVertical="true"
                android:layout_marginEnd="16dp"
                tools:text="04:44"/>

            <ImageButton
                android:id="@+id/nowPlayingThumbsDown_imageButton"
                android:layout_width="48dp"
                android:layout_height="wrap_content"
                android:layout_alignParentStart="true"
                android:layout_centerVertical="true"
                android:background="@null"
                android:src="@drawable/rate_thumb_down_empty"
                android:visibility="invisible"/>

            <ImageButton
                android:id="@+id/nowPlayingThumbsUp_imageButton"
                android:layout_width="48dp"
                android:layout_height="wrap_content"
                android:layout_alignParentEnd="true"
                android:layout_centerVertical="true"
                android:background="@null"
                android:src="@drawable/rate_thumb_up_empty"
                android:visibility="invisible"/>
        </RelativeLayout>

        <org.adw.library.widgets.discreteseekbar.DiscreteSeekBar
            android:id="@+id/nowPlaying_seekBar"
            android:layout_width="match_parent"
            android:layout_height="70dp"
            android:layout_below="@id/albumArtLayout"
            android:layout_marginLeft="-8.4dp"
            android:layout_marginRight="-8.4dp"
            android:layout_marginTop="-16.5dp"
            app:dsb_trackColor="@color/clear"
            app:dsb_allowTrackClickToDrag="true"/>
    </RelativeLayout>

</RelativeLayout>

**Comment by AnderWeb** [comment]
Weird, I've just tried your layout and doesn't show any strange clipping (tested on an 4.4 emulator).
I just copied your XML into the sample activity activity_main.xml. Then removed all the missing styles, replaced all missing drawables with @drawable/ic_launcher, replaced our CircleImageView with a regular ImageView, and changed the discreteSeekbr id with @+id/discrete1 so it doesn't need code changes into MainActivity.java.
Running it doesn't show any clipping issues for me as specified.
Please, do the same test yourself and report back to see if it's something missing. Also please report back about what devices/android versions/emlator options/whatever you have tested the issue with.

**Comment by AOrobator** [comment]
I'm having trouble reproducing the issue outside of where it's being used in my app as well. For context, this is a music playing app and the seekbar is constantly being updated by another thread. However this doesn't seem to be the cause of the issue because I've disabled the thread on the now playing screen where the seekbar is being used and still observed the clipping behavior. I'll continue looking into how to reproduce this, but it may help to know that the view only clips on the left side when it is being dragged to the left.

**Comment by AOrobator** [comment]
I've found the source of the problem. 
Repro steps:

Have an activity with the following layout:

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">
    
        <org.adw.library.widgets.discreteseekbar.DiscreteSeekBar
            android:layout_centerInParent="true"
            android:id="@+id/nowPlaying_seekBar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>
    
    </RelativeLayout>

Then in the manifest, put this line in the activity tag `android:hardwareAccelerated="false"`
